# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventBriteSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EventBriteSample
pod 'SwiftyJSON'
pod 'SDWebImage'
pod 'Alamofire'
pod 'AppCenter'
end

target 'EventBriteSampleTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for EventBriteSample
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'AppCenter'
end
